# https://authjs.dev/getting-started/deployment
services:
  app:
    build: .
    container_name: vercel-basic-replica
    restart: unless-stopped
    ports:
      - "43001:3001"
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - AUTH_TRUST_HOST="true"
  redis:
    image: redis:latest
    container_name: vercel-basic-replica-redis
    command: redis-server
    restart: unless-stopped
